### ISSUE TITLE
Убрать link preview

### ISSUE THREAD

**Issue by VadimCpp** [VadimCpp/pyfirstbotbot#6]
При отправке ботом сообщения возможно явно указать, чтобы телеграм не подгружал информацию по ссылке. Вот тут:
https://core.telegram.org/method/messages.sendMessage

Параметр **no_webpage**

Необходимо разобраться с telebot api и отключить генерацию link preview

**Comment by s0ull3ss** [comment]
Сделано. Не совсем понятно, зачем ссылка на api telegram, если мы напрямую не работаем с ним (работаем через [либу](https://github.com/eternnoir/pyTelegramBotAPI))?
#7
